[package]
name = "txlib"
version = "0.1.1"
edition = "2021"

[dependencies]
epub = "2.0.0"
glob = "0.3.1"
chrono = "0.4.23"
dirs = "4.0.0"
open = "3.2.0"
clap = { version = "4.1.4", features = ["derive"] }

[profile.release]
lto = true